---
- hosts: master
  remote_user: root

  tasks:
   - name: Adding etcd servers
     lineinfile:
        name: /etc/kubernetes/apiserver
        state: present
        regexp: '^KUBE_ETCD_SERVERS='
        line: 'KUBE_ETCD_SERVERS="--etcd-servers=http://kube-master:2379"'
   - name: Adding kube api addresses
     lineinfile:
        name: /etc/kubernetes/apiserver
        state: present
        regexp: '^KUBE_API_ADDRESS='
        line: 'KUBE_API_ADDRESS="--address=0.0.0.0"'
   - name: Adding kube api port
     lineinfile:
        name: /etc/kubernetes/apiserver
        state: present
        regexp: '^KUBE_API_PORT='
        line: 'KUBE_API_PORT="--port=8080"'
   - name: Adding kubelet port
     lineinfile:
        name: /etc/kubernetes/apiserver
        state: present
        regexp: '^KUBELET_PORT='
        line: 'KUBELET_PORT="--kubelet-port=10250"'

   - name: Adding cube master server
     lineinfile:
        name: /etc/kubernetes/config
        state: present
        regexp: '^KUBE_MASTER='
        line: 'KUBE_MASTER="--master=http://kube-master:8080"'
   - name: Adding etcd listen client URLS
     lineinfile:
        name: /etc/etcd/etcd.conf
        state: present
        regexp: '^ETCD_LISTEN_CLIENT_URLS='
        line: 'ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"'
   - name: Adding etcd advertise client URLS
     lineinfile:
        name: /etc/etcd/etcd.conf
        state: present
        regexp: '^ETCD_ADVERTISE_CLIENT_URLS='
        line: 'ETCD_ADVERTISE_CLIENT_URLS="http://0.0.0.0:2379"'


