---
- hosts: master
  remote_user: root

  tasks:
   - name: Adding etcd servers
     lineinfile:
        name: /etc/kubernetes/apiserver
        state: present
        regexp: '^KUBE_ETCD_SERVERS='
        line: 'KUBE_ETCD_SERVERS="--etcd-servers=http://kube-master:2379"'
   - name: Adding etcd servers
     lineinfile:
        name: /etc/kubernetes/config
        state: present
        regexp: '^KUBE_ETCD_SERVERS='
        line: 'KUBE_ETCD_SERVERS="--etcd-servers=http://kube-master:2379"'
   - name: Adding kube api addresses
     lineinfile:
        name: /etc/kubernetes/apiserver
        state: present
        regexp: '^KUBE_API_ADDRESS='
        line: 'KUBE_API_ADDRESS="--address=0.0.0.0"'
   - name: Adding kube api KEY
     lineinfile:
        name: /etc/kubernetes/apiserver
        state: present
        regexp: '^KUBE_API_ARGS='
        line: 'KUBE_API_ARGS="--service-account_key_file=/etc/kubernetes/servieaccount.key"'
   - name: Adding kube api port
     lineinfile:
        name: /etc/kubernetes/apiserver
        state: present
        regexp: '^KUBE_API_PORT='
        line: 'KUBE_API_PORT="--port=8080"'
   - name: Adding kubelet port
     lineinfile:
        name: /etc/kubernetes/apiserver
        state: present
        regexp: '^KUBELET_PORT='
        line: 'KUBELET_PORT="--kubelet-port=10250"'

   - name: Adding cube master server
     lineinfile:
        name: /etc/kubernetes/config
        state: present
        regexp: '^KUBE_MASTER='
        line: 'KUBE_MASTER="--master=http://kube-master:8080"'
   - name: Adding etcd listen client URLS
     lineinfile:
        name: /etc/etcd/etcd.conf
        state: present
        regexp: '^ETCD_LISTEN_CLIENT_URLS='
        line: 'ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"'
   - name: Adding etcd advertise client URLS
     lineinfile:
        name: /etc/etcd/etcd.conf
        state: present
        regexp: '^ETCD_ADVERTISE_CLIENT_URLS='
        line: 'ETCD_ADVERTISE_CLIENT_URLS="http://0.0.0.0:2379"'
   - name: Adding kube api key to controller-manager
     lineinfile:
        name: /etc/kubernetes/controller-manager
        state: present
        regexp: '^KUBE_CONTROLLER_MANAGER_ARGS='
        line: 'KUBE_CONTROLLER_MANAGER_ARGS="--service_account_private_key_file=/etc/kubernetes/servieaccount.key"'
   - name: Adding Flannel endpoint
     lineinfile:
        name: /etc/sysconfig/flanneld
        state: present
        regexp: '^FLANNEL_ETCD_ENDPOINTS='
        line: 'FLANNEL_ETCD_ENDPOINTS="http://kube-master:2379"'
   - name: Adding Flannel Prefix
     lineinfile:
        name: /etc/sysconfig/flanneld
        state: present
        regexp: '^FLANNEL_ETCD_PREFIX='
        line: 'FLANNEL_ETCD_PREFIX="/kube-centos/network"'

- hosts: minions
  remote_user: root
  tasks:

   - name: Adding cube master server
     lineinfile:
        name: /etc/kubernetes/config
        state: present
        regexp: '^KUBE_MASTER='
        line: 'KUBE_MASTER="--master=http://kube-master:8080"'

   - name: Adding etcd servers
     lineinfile:
        name: /etc/kubernetes/apiserver
        state: present
        regexp: '^KUBE_ETCD_SERVERS='
        line: 'KUBE_ETCD_SERVERS="--etcd-servers=http://kube-master:2379"'
   - name: Adding etcd servers
     lineinfile:
        name: /etc/kubernetes/config
        state: present
        regexp: '^KUBE_ETCD_SERVERS='
        line: 'KUBE_ETCD_SERVERS="--etcd-servers=http://kube-master:2379"'
   - name: Adding kubelete addresses
     lineinfile:
        name: /etc/kubernetes/kubelet
        state: present
        regexp: '^KUBELET_ADDRESS='
        line: 'KUBELET_ADDRESS="--address=0.0.0.0"'
   - name: Adding kubelete port
     lineinfile:
        name: /etc/kubernetes/kubelet
        state: present
        regexp: '^KUBELET_PORT='
        line: 'KUBELET_PORT="--port=10250"'
   - name: Adding kubelete hostname
     lineinfile:
        name: /etc/kubernetes/kubelet
        state: present
        regexp: '^KUBELET_HOSTNAME='
        line: 'KUBELET_HOSTNAME="--hostname-override={{ ansible_hostname }}"'
   - name: Adding kubelete api-server
     lineinfile:
        name: /etc/kubernetes/kubelet
        state: present
        regexp: '^KUBELET_API_SERVER='
        line: 'KUBELET_API_SERVER="--api-servers=http://kube-master:8080"'
   - name: Adding kube api KEY
     lineinfile:
        name: /etc/kubernetes/apiserver
        state: present
        regexp: '^KUBE_API_ARGS='
        line: 'KUBE_API_ARGS="--service-account_key_file=/etc/kubernetes/serviceaccount.key"'
   - name: Adding Flannel endpoint
     lineinfile:
        name: /etc/sysconfig/flanneld
        state: present
        regexp: '^FLANNEL_ETCD_ENDPOINTS='
        line: 'FLANNEL_ETCD_ENDPOINTS="http://kube-master:2379"'
   - name: Adding Flannel Prefix
     lineinfile:
        name: /etc/sysconfig/flanneld
        state: present
        regexp: '^FLANNEL_ETCD_PREFIX='
        line: 'FLANNEL_ETCD_PREFIX="/kube-centos/network"'
